MazakaNet/Controllers/TodoIstApiController.cs
using System.Net.Http.Headers;
using System.Text.Json;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using NuGet.Protocol;
using Todoist.Net;
using Todoist.Net.Models;
using Task = MazakaNet.Models.Task.Task;

namespace MazakaNet.Controllers
{
    [Route("api/[controller]/[action]")]
    [ApiController]
    [Authorize]
    public class TodoIstApiController : Controller
    {
        private static IConfiguration _configuration;
        
        public TodoIstApiController(IConfiguration configuration)
        {
            _configuration = configuration;
        }



        
        public async void AddItems(string content, string description)
        {
            var token = _configuration.GetValue<string>("Todoist:Token");
             ITodoistClient client = new TodoistClient(token);
            var newItem = new Item(content);
            newItem.Description = description;
            newItem.Collapsed = false;

                        var task = await client.Items.AddAsync(newItem);
                        
        }

        [HttpGet]
        public async Task<IActionResult> AddProject()
        {
            string randomGuid = new Guid().ToString();
            var token = _configuration.GetValue<string>("Todoist:Token");
            HttpClient client = new HttpClient();
client.DefaultRequestHeaders.Add("Authorization","Bearer "+token);
client.DefaultRequestHeaders.Add("X-Request-Id", randomGuid);
client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

var response=await client.PostAsJsonAsync("https://api.todoist.com/rest/v2/projects",new
{
name="Cagri Karaca"

});

response.EnsureSuccessStatusCode();
var result = await response.Content.ReadAsStreamAsync();

return Ok(result);
        }

        //[HttpGet]
        //public async Task<IActionResult> updateAssigner()
        //{
        //    var token = _configuration.GetValue<string>("Todoist:Token");

        //    string randomGuid = new Guid().ToString();
        //    string projectId = (await new TodoistClient(token).Items.GetAsync()).FirstOrDefault(project=>project.Content=="des")?.Id.ToString();

        //    HttpClient client = new HttpClient();
        //    client.DefaultRequestHeaders.Add("Authorization", "Bearer " + token);
        //    client.DefaultRequestHeaders.Add("X-Request-Id", randomGuid);
        //    client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

        //    var response = await client.PostAsJsonAsync("https://api.todoist.com/rest/v2/tasks/"+projectId, new
        //    {
                
        //        description="Yeni degiştirilen kod"

        //    });

        //    response.EnsureSuccessStatusCode();
        //    var result = await response.Content.ReadAsStreamAsync();

        //    return Ok(result);
        //}

        [HttpGet]
        public async Task<IActionResult> GetProjects()
        {
            var token = _configuration.GetValue<string>("Todoist:Token");
            ITodoistClient client = new TodoistClient(token);

            var projects = await client.Projects.GetAsync();
            return View(projects);
        }
        [HttpGet]
        public async Task<IActionResult> GetUser()
        {
            var token = _configuration.GetValue<string>("Todoist:Token");
            ITodoistClient client = new TodoistClient(token);

            var user = await client.Users.GetCurrentAsync();
            return Ok(user);
        }
        [HttpGet]
        public async Task<IActionResult> getItems()
        {
            var token = _configuration.GetValue<string>("Todoist:Token");
            ITodoistClient client = new TodoistClient(token);
var items = await client.Items.GetAsync();

return View(items);
        }

        [HttpGet]
        public async Task<IActionResult> getAllResources()
        {
            var token = _configuration.GetValue<string>("Todoist:Token");
            ITodoistClient client = new TodoistClient(token);
            
            var resources = await client.GetResourcesAsync();

            return View(resources);
        }
    }
}

MazakaNet/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using accountService =MazakaNet.Services.AccountServices;


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - MazakaNet</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/MazakaNet.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MazakaNet</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Panel">Panel</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="TodoIstApi" asp-action="getAllResources">Resources</a>
                    </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TodoIstApi" asp-action="getItems">Items</a>
                        </li>  
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="TodoIstApi" asp-action="GetProjects">Projects</a>
                    </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TodoIstApi" asp-action="GetUser">User</a>
                        </li>
                    @{
                        
                        if (accountService._signInManager.IsSignedIn(User))
                    {
                        var user = await accountService._userManager.GetUserAsync(User);
                        var roles = await accountService._userManager.GetRolesAsync(user);
                        var username = accountService._userManager.GetUserName(User);

                        <li class="nav-item">
                            <a class="nav-link" href="#">@roles.First()</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Hello @username</a>
                        </li>
                        <li class="nav-item">
                            <form id="logoutForm" method="post" class="form-inline" asp-controller="Account"
                                  asp-action="LogOut">
                                <button type="submit" class="btn nav-link">Logout</button>
                            </form>
                        </li>
                    }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                            <li class="nav-item">
                                <form id="logoutForm" method="post" class="form-inline" asp-controller="Account"
                                      asp-action="Logout">
                                    <button type="submit" class="btn nav-link">Logout</button>
                                </form>
                            </li>
                        }
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2022 - MazakaNet - <a asp-area="" asp-controller="Home" asp-action="Panel">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", false)
</body>
</html>